# Application Name
spring.application.name=MuseoConnect

# MongoDB Configuration
#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
server.port=${PORT:8080}
spring.data.mongodb.database=museumDB
spring.data.mongodb.uri=${MONGO_URL}
spring.data.mongodb.auto-index-creation=true
spring.main.lazy-initialization=true
#spring.data.mongodb.auto-index-creation=true

# JWT Secret: must be at least 256-bit base64 encoded
# This key is 256-bit and valid for HMAC-SHA256
#jwt.secret=dGhpc19pc19hX3ZhbGlkX2Jhc2U2NF9zZWNyZXQxMjM0NTY=
#jwt.expiration=3600000
server.forward-headers-strategy=framework
