# Application Name
spring.application.name=MuseoConnect

# Server Port (Required for Railway)
server.port=8081


# MongoDB (Use Railway variable)
#spring.data.mongodb.uri=mongodb://localhost:27017/museodb

spring.data.mongodb.uri = mongodb+srv://agarwalshubh1972004:root@cluster0.810s0zu.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=museumDB
spring.data.mongodb.auto-index-creation=true


jwt.secret=testsecret123456789012345678901234
jwt.expiration=3600000
#spring.data.mongodb.ssl.enabled=true
server.forward-headers-strategy=framework

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=yadavaarav200@gmail.com
spring.mail.password=rmifultghlbngnpg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.data.redis.host=host.docker.internal
spring.data.redis.port=6379

# Disable debug in production
spring.mail.properties.mail.debug=false